### ISSUE TITLE
Confirm AWS plugin packaging bug

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent-aws-plugins#8]
**Acceptance criteria:**

- [x] Using a docker environment, pip install covalent-aws-plugins.
- [x] In a python file, check that with only this pip install, you're able to import the following aws executors: batch, ecs, lambda, braket, ec2
- [x] Leave a comment confirming that the bug was reproduced (or not).
- [x] Copy paste the docker file and python script for future use in this issue.

**Comment by scottwn** [comment]
1. Build an image using this [Dockerfile](https://github.com/AgnostiqHQ/covalent-aws-plugins/blob/069d11bd6f57f378f86a88407a5b66725688d633/tests/functional_tests/Dockerfile), e.g.
```
cd tests/functional_tests
docker build -t covalent-plugin-testing .
```
2. Log into the container
```
docker run --rm -it --entrypoint bash covalent-plugin-testing
```
3. Install `covalent-aws-plugins` for the branch you want to test
```
cd covalent-aws-plugins
git checkout my-branch
python3.8 setup.py sdist
pip install dist/*.tar.gz
```
4. open a Python shell
```
python3.8
```
5. attempt to import the executors
```
>>> from covalent.executor import AWSBatchExecutor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AWSBatchExecutor' from 'covalent.executor' (/usr/local/lib/python3.8/dist-packages/covalent/executor/__init__.py)
```

**Comment by FyzHsn** [comment]
These instructions worked for me! Thanks Scott. Closing this issue.

Also, I found the same results for Conda as expected.
