### ISSUE TITLE
Fix packaging bug

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent-aws-plugins#9]
**Acceptance criteria:**

- [ ] Find fix for packaging bug via git submodule tool: https://git-scm.com/book/en/v2/Git-Tools-Submodules
- [ ] 2 independent validation that the fix resolves the packaging bug.
- [ ] One thing to keep in mind is that when we install `covalent-aws-batch` for example, it requires `covalent-aws-plugins` and should NOT install each of the other executors. 
- [ ] While I won't block the pushing of this fix due to a lack of testing, write down / scope out the addition of a test to ensure that the packaging is working as intended.

**Backend logic:**

```
# covalent-awsbatch-plugin/requirements.txt
covalent-aws-plugins[batch]==[version_num]

In covalent-aws-plugins's extras_require={"batch": "covalent-awsbatch-plugin==ver"}
```

**Comment by scottwn** [comment]
in https://github.com/AgnostiqHQ/covalent-aws-plugins/blob/develop/setup.py
```
'extras_require': {
  None: ['covalent-awsbatch-plugin','covalent-ecs-plugin'], #add all the AWS plugins
  'base': []
}

in https://github.com/AgnostiqHQ/covalent-awsbatch-plugin/blob/develop/requirements.txt and the other executor reqs
```
covalent-aws-plugins[base]==0.1.0rc0
```

**Comment by FyzHsn** [comment]
Also, using a conda environment, I see that `pip install covalent-aws-plugins` does not install any of the aws plugins.

Before aws plugin install:
![Screen Shot 2022-09-28 at 4.06.16 PM.png](https://images.zenhubusercontent.com/61a156d4b7ec2333c6d855f3/38c705e6-2bba-4d3e-8d24-3ff1bdf146e9)

After aws plugin install:
![Screen Shot 2022-09-28 at 4.04.58 PM.png](https://images.zenhubusercontent.com/61a156d4b7ec2333c6d855f3/a81b9e7f-6ab3-4b67-824e-16fee7c4c472)

**Comment by FyzHsn** [comment]
@scottwn How do we ensure that the specific covalent aws plugin executor versions in the covalent-aws-plugins requirements file are bumped up when there's a new release?
